<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrganismoSeeder extends Seeder
{
    public function run(): void
    {
        // DB::table('organismos')->insert([
        //     ['depe_codi' => 4112010, 'depe_nomb' => 'DESPACHO DEL ALCALDE'],
        //     ['depe_codi' => 4112020, 'depe_nomb' => 'SECRETARIA DE GOBIERNO'],
        //     ['depe_codi' => 4112030, 'depe_nomb' => 'Oficina de la Secretaría Privada'],
        //     ['depe_codi' => 4112040, 'depe_nomb' => 'Oficina Asesora de Transparencia'],
        //     ['depe_codi' => 4112050, 'depe_nomb' => 'Oficina de Relaciones y Cooperación'],
        //     ['depe_codi' => 4112060, 'depe_nomb' => 'Oficina de Comunicaciones'],
        //     ['depe_codi' => 4121010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE GESTION JURIDICA PUBLICA'],
        //     ['depe_codi' => 4121030, 'depe_nomb' => 'Subdirección de Doctrina y Asuntos Normativos'],
        //     ['depe_codi' => 4121040, 'depe_nomb' => 'Subdirección de Defensa Judicial y Prevención del Daño Antijurídico'],
        //     ['depe_codi' => 4123010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE CONTROL INTERNO'],
        //     ['depe_codi' => 4124010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE CONTROL DISCIPLINARIO INTERNO'],
        //     ['depe_codi' => 4131010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE HACIENDA MUNICIPAL'],
        //     ['depe_codi' => 4131020, 'depe_nomb' => 'Subdireccion de Finanzas Publicas'],
        //     ['depe_codi' => 4131030, 'depe_nomb' => 'Subdireccion de Tesoreria Municipal'],
        //     ['depe_codi' => 4131031, 'depe_nomb' => 'Oficina Tecnica Operativa de Cobro Persuasivo'],
        //     ['depe_codi' => 4131032, 'depe_nomb' => 'Oficina Tecnica Operativa de Cobro Coactivo'],
        //     ['depe_codi' => 4131040, 'depe_nomb' => 'Subdireccion de Impuestos y Rentas Municipales'],
        //     ['depe_codi' => 4131041, 'depe_nomb' => 'Oficina Tecnica Operativa de Fiscalizacion y Determinacion de Rentas'],
        //     ['depe_codi' => 4131050, 'depe_nomb' => 'Subdireccion de Catastro Municipal'],
        //     ['depe_codi' => 4131060, 'depe_nomb' => 'Contaduria General del Municipio de Santiago de Cali'],
        //     ['depe_codi' => 4132010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE PLANEACION MUNICIPAL'],
        //     ['depe_codi' => 4132030, 'depe_nomb' => 'Subdireccion de Espacio Publico y Ordenamiento Urbanistico'],
        //     ['depe_codi' => 4132040, 'depe_nomb' => 'Subdireccion de Desarrollo Integral'],
        //     ['depe_codi' => 4132050, 'depe_nomb' => 'Subdireccion de Planificacion del Territorio'],
        //     ['depe_codi' => 4133010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE GESTION DEL MEDIO AMBIENTE'],
        //     ['depe_codi' => 4133020, 'depe_nomb' => 'Subdireccion de Gestion de Calidad Ambiental'],
        //     ['depe_codi' => 4133030, 'depe_nomb' => 'Subdireccion de Gestion Integral de Ecosistemas y Unidad Municipal de Asistencia Tecnica –UMATA'],
        //     ['depe_codi' => 4134010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE TECNOLOGIAS DE LA INFORMACION Y LAS COMUNICACIONES'],
        //     ['depe_codi' => 4134020, 'depe_nomb' => 'Subdireccion de Tecnologia Digital'],
        //     ['depe_codi' => 4134030, 'depe_nomb' => 'Subdireccion de Innovacion Digital'],
        //     ['depe_codi' => 4135010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE CONTRATACION PUBLICA'],
        //     ['depe_codi' => 4135020, 'depe_nomb' => 'Subdireccion de Abastecimiento Estrategico'],
        //     ['depe_codi' => 4135030, 'depe_nomb' => 'Subdireccion de Gestion del Conocimiento y la Innovacion'],
        //     ['depe_codi' => 4137010, 'depe_nomb' => 'DEPARTAMENTO ADMINISTRATIVO DE DESARROLLO E INNOVACION INSTITUCIONAL'],
        //     ['depe_codi' => 4137020, 'depe_nomb' => 'Subdireccion de Gestion Organizacional'],
        //     ['depe_codi' => 4137030, 'depe_nomb' => 'Subdireccion de Tramites, Servicios y Gestion Documental'],
        //     ['depe_codi' => 4137040, 'depe_nomb' => 'Subdireccion de Gestion Estrategica del Talento Humano'],
        //     ['depe_codi' => 4143010, 'depe_nomb' => 'SECRETARIA DE EDUCACION'],
        //     ['depe_codi' => 4143020, 'depe_nomb' => 'Subsecretaria Administrativa y Financiera'],
        //     ['depe_codi' => 4143040, 'depe_nomb' => 'Subsecretaria de Planeacion Sectorial'],
        //     ['depe_codi' => 4143050, 'depe_nomb' => 'Subsecretaria de Cobertura Educativa'],
        //     ['depe_codi' => 4143060, 'depe_nomb' => 'Subsecretaria de Calidad Educativa'],
        //     ['depe_codi' => 4145010, 'depe_nomb' => 'SECRETARIA DE SALUD'],
        //     ['depe_codi' => 4145020, 'depe_nomb' => 'Subsecretaria de Promocion, Prevencion y Produccion Social de la Salud'],
        //     ['depe_codi' => 4145030, 'depe_nomb' => 'Subsecretaria  Proteccion de la Salud  y Prestacion de Servicios'],
        //     ['depe_codi' => 4146010, 'depe_nomb' => 'SECRETARIA DE BIENESTAR SOCIAL'],
        //     ['depe_codi' => 4146020, 'depe_nomb' => 'Subsecretaria de Poblaciones y Etnias'],
        //     ['depe_codi' => 4146030, 'depe_nomb' => 'Subsecretaria de Atencion Integral a Victimas'],
        //     ['depe_codi' => 4146040, 'depe_nomb' => 'Subsecretaria de Equidad de Genero'],
        //     ['depe_codi' => 4146050, 'depe_nomb' => 'Subsecretaria de la Primera Infancia'],
        //     ['depe_codi' => 4147010, 'depe_nomb' => 'SECRETARIA DE VIVIENDA SOCIAL Y HABITAT'],
        //     ['depe_codi' => 4147040, 'depe_nomb' => 'Subsecretaria de Mejoramiento Integral y Legalizacion'],
        //     ['depe_codi' => 4147050, 'depe_nomb' => 'Subsecretaria de Gestion de Suelo y Oferta de Vivienda'],
        //     ['depe_codi' => 4148010, 'depe_nomb' => 'SECRETARIA DE CULTURA'],
        //     ['depe_codi' => 4148020, 'depe_nomb' => 'Subsecretaria de Patrimonio, Bibliotecas e Infraestructura Cultural'],
        //     ['depe_codi' => 4148021, 'depe_nomb' => 'Red de Bibliotecas LEO 3'],
        //     ['depe_codi' => 4148022, 'depe_nomb' => 'Red de Bibliotecas LEO 2'],
        //     ['depe_codi' => 4148023, 'depe_nomb' => 'Red de Bibliotecas LEO 5'],
        //     ['depe_codi' => 4148024, 'depe_nomb' => 'Red de Bibliotecas LEO 4'],
        //     ['depe_codi' => 4148025, 'depe_nomb' => 'Red de Bibliotecas LEO 1'],
        //     ['depe_codi' => 4148030, 'depe_nomb' => 'Subsecretaria de Artes, Creacion y Promocion Cultural'],
        //     ['depe_codi' => 4148050, 'depe_nomb' => 'Unidad Administrativa Especial del Teatro Municipal'],
        //     ['depe_codi' => 4148060, 'depe_nomb' => 'Unidad Administrativa Especial Estudios Takeshima'],
        //     ['depe_codi' => 4151010, 'depe_nomb' => 'SECRETARIA DE INFRAESTRUCTURA'],
        //     ['depe_codi' => 4151020, 'depe_nomb' => 'Subsecretaria de Infraestructura y Mantenimiento Vial'],
        //     ['depe_codi' => 4151030, 'depe_nomb' => 'Subsecretaria de Apoyo Tecnico'],
        //     ['depe_codi' => 4152010, 'depe_nomb' => 'SECRETARIA DE MOVILIDAD'],
        //     ['depe_codi' => 4152014, 'depe_nomb' => 'Oficina de contravenciones'],
        //     ['depe_codi' => 4152020, 'depe_nomb' => 'Subsecretaria de Movilidad Sostenible y Seguridad Vial'],
        //     ['depe_codi' => 4152030, 'depe_nomb' => 'Subsecretaria de Servicios de Movilidad'],
        //     ['depe_codi' => 4161010, 'depe_nomb' => 'SECRETARIA DE SEGURIDAD Y JUSTICIA'],
        //     ['depe_codi' => 4161040, 'depe_nomb' => 'Subsecretaria de la Politica de Seguridad'],
        //     ['depe_codi' => 4161050, 'depe_nomb' => 'Subsecretaria de Acceso a Servicios de Justicia'],
        //     ['depe_codi' => 4161060, 'depe_nomb' => 'Subsecretaria de Inspeccion, Vigilancia y Control'],
        //     ['depe_codi' => 4162010, 'depe_nomb' => 'SECRETARIA DEL DEPORTE Y LA RECREACION'],
        //     ['depe_codi' => 4162020, 'depe_nomb' => 'Subsecretaria de Fomento'],
        //     ['depe_codi' => 4162030, 'depe_nomb' => 'Subsecretaria de Infraestructura Deportiva y Recreativa'],
        //     ['depe_codi' => 4163001, 'depe_nomb' => 'SECRETARIA DE GESTION DEL RIESGO DE EMERGENCIAS Y DESASTRES'],
        //     ['depe_codi' => 4163010, 'depe_nomb' => 'Subsecretaria para el Conocimiento y la Reduccion del Riesgo'],
        //     ['depe_codi' => 4163020, 'depe_nomb' => 'Subsecretaria para el Manejo de Desastres'],
        //     ['depe_codi' => 4164010, 'depe_nomb' => 'SECRETARIA DE PAZ Y CULTURA CIUDADANA'],
        //     ['depe_codi' => 4164020, 'depe_nomb' => 'Subsecretaria de Prevencion y Cultura Ciudadana'],
        //     ['depe_codi' => 4164030, 'depe_nomb' => 'Subsecretaria de Derechos Humanos y Construccion de Paz'],
        //     ['depe_codi' => 4171010, 'depe_nomb' => 'SECRETARIA DE DESARROLLO ECONOMICO'],
        //     ['depe_codi' => 4171020, 'depe_nomb' => 'Subsecretaria de Cadenas de Valor'],
        //     ['depe_codi' => 4171030, 'depe_nomb' => 'Subsecretaria de Servicios Productivos y Comercio Colaborativo'],
        //     ['depe_codi' => 4172010, 'depe_nomb' => 'SECRETARIA DE TURISMO'],
        //     ['depe_codi' => 4173020, 'depe_nomb' => 'Subsecretaria de Promocion y Fortalecimiento de la Participacion'],
        //     ['depe_codi' => 4173030, 'depe_nomb' => 'Subsecretaria de Territorios de Inclusion y Oportunidades Urbano y Rural'],
        //     ['depe_codi' => 4173401, 'depe_nomb' => 'CALI 1'],
        //     ['depe_codi' => 4173402, 'depe_nomb' => 'CALI 2'],
        //     ['depe_codi' => 4173403, 'depe_nomb' => 'CALI 3'],
        //     ['depe_codi' => 4173404, 'depe_nomb' => 'CALI 4'],
        //     ['depe_codi' => 4173405, 'depe_nomb' => 'CALI 5'],
        //     ['depe_codi' => 4173406, 'depe_nomb' => 'CALI 6'],
        //     ['depe_codi' => 4173407, 'depe_nomb' => 'CALI 7'],
        //     ['depe_codi' => 4173408, 'depe_nomb' => 'CALI 8'],
        //     ['depe_codi' => 4173409, 'depe_nomb' => 'CALI 9'],
        //     ['depe_codi' => 41734010, 'depe_nomb' => 'CALI 10'],
        //     ['depe_codi' => 41734011, 'depe_nomb' => 'CALI 11'],
        //     ['depe_codi' => 41734012, 'depe_nomb' => 'CALI 12'],
        //     ['depe_codi' => 41734013, 'depe_nomb' => 'CALI 13'],
        //     ['depe_codi' => 41734014, 'depe_nomb' => 'CALI 14'],
        //     ['depe_codi' => 41734015, 'depe_nomb' => 'CALI 15'],
        //     ['depe_codi' => 41734016, 'depe_nomb' => 'CALI 16'],
        //     ['depe_codi' => 41734017, 'depe_nomb' => 'CALI 17'],
        //     ['depe_codi' => 41734018, 'depe_nomb' => 'CALI 18'],
        //     ['depe_codi' => 41734019, 'depe_nomb' => 'CALI 19'],
        //     ['depe_codi' => 41734020, 'depe_nomb' => 'CALI 20'],
        //     ['depe_codi' => 41734021, 'depe_nomb' => 'CALI 21'],
        //     ['depe_codi' => 41734023, 'depe_nomb' => 'CALI RURAL'],
        //     ['depe_codi' => 4181010, 'depe_nomb' => 'Unidad Administrativa Especial de Gestion de Bienes y Servicios'],
        //     ['depe_codi' => 4182010, 'depe_nomb' => 'Unidad Administrativa Especial de Servicios Publicos Municipales'],
        //     ['depe_codi' => 4183010, 'depe_nomb' => 'Unidad Administrativa Especial de Protección Animal']
        // ]);

        DB::table('organismos')->insert([
            [ 'depe_codi' => 4132010,'depe_nomb' => 'Departamento Administrativo de Planeacion Municipal'],
            [ 'depe_codi' => 4133010,'depe_nomb' => 'Departamento Administrativo de Gestion del Medio Ambiente - DAGMA'],
            [ 'depe_codi' => 4131010,'depe_nomb' => 'Departamento Administrativo de Hacienda Municipal'],
            [ 'depe_codi' => 4151010,'depe_nomb' => 'Secretaria de Infraestructura'],
            [ 'depe_codi' => 4181010,'depe_nomb' => 'Unidad Administrativa Especial de Gestion de Bienes y Servicios'],
            [ 'depe_codi' => 4131050,'depe_nomb' => 'Subdireccion de Catastro'],
            [ 'depe_codi' => 4162010,'depe_nomb' => 'Secretaria del Deporte y la Recreacion'],
            [ 'depe_codi' => 4131030,'depe_nomb' => 'Subdireccion de Tesoreria Municipal'],
            [ 'depe_codi' => 4131040,'depe_nomb' => 'Subdireccion de Impuestos y Rentas'],
            [ 'depe_codi' => 4148010,'depe_nomb' => 'Secretaria de Cultura'],
            [ 'depe_codi' => 4161010,'depe_nomb' => 'Secretaria de Seguridad y Justicia'],
            [ 'depe_codi' => 4152010,'depe_nomb' => 'Secretaria de Movilidad'],
            [ 'depe_codi' => 4147010,'depe_nomb' => 'Secretaria de Vivienda Social y Habitat'],
        //     [ 'depe_nomb' => 'Secretaria de Desarrollo Territorial y Participacion Ciudadana'],
            [ 'depe_codi' => 4143010,'depe_nomb' => 'Secretaria de Educacion'],
            [ 'depe_codi' => 4145010,'depe_nomb' => 'Secretaria de Salud Publica'],
            [ 'depe_codi' => 4145011,'depe_nomb' => 'Notificaciones avisos hacienda'],

        ]);
        
    }
}
